# Generated by Django 3.0.8 on 2020-07-16 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('products', '0003_auto_20200715_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.Category'),
        ),
    ]
