# Generated by Django 3.0.8 on 2020-07-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20200713_0148'),
        ('products', '0004_auto_20200716_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prov',
            new_name='cat_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AddField(
            model_name='product',
            name='prov_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Provider'),
        ),
    ]
