# Generated by Django 3.0.8 on 2020-07-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200716_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prov_id',
            new_name='prov',
        ),
    ]
