# Generated by Django 3.1 on 2020-08-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
