# Generated by Django 3.1 on 2020-08-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200806_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
