# Generated by Django 3.1 on 2020-08-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20200713_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1),
        ),
    ]
