# Generated by Django 2.1.5 on 2020-08-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_auto_20200806_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
